- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python35-jobs-neutron
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
