- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstack-python35-jobs-neutron
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
